// src/components/WagonSkills.tsx
import * as React from 'react';
import { styled } from '@mui/material/styles';

const Skills = styled('div')({
	display: 'flex',
	flexDirection: 'column',
	alignSelf: 'center',
})
const Container = styled('div')({
	margin: '.5em 0',
	positon: 'relative',
	width: '22.5em',
})
const Title = styled('h3')({
	color: '#ffffff',
	fontWeight: 300,
	fontSize: '0.8em',
	letterSpacing: '0.145em',
	textTransform: 'uppercase',
	width: '10em',
})
const OuterBar = styled('div')({
	marginTop: '1em',
	background: '#333333',
	height: '0.75em',
})
const InnerBarPython = styled('div')({
	width: '90%',
  background: '#08475f',
  height: '0.75em',
  transform: 'scaleX(0)',
  transformOrigin: '0 0',
	animation: 'fill-bar 1s forwards',

	'@keyframes fill-bar': {
		'to': {
			transform: 'scaleX(1)',
		}
	}
})
const InnerBarDjango = styled('div')({
	width: '90%',
  background: '#13583e',
  height: '0.75em',
  transform: 'scaleX(0)',
  transformOrigin: '0 0',
	animation: 'fill-bar 1s forwards',

	'@keyframes fill-bar': {
		'to': {
			transform: 'scaleX(1)',
		}
	}
})
const InnerBarJavascript = styled('div')({
	width: '95%',
  background: '#ecd51d',
  height: '0.75em',
  transform: 'scaleX(0)',
  transformOrigin: '0 0',
	animation: 'fill-bar 1s forwards',

	'@keyframes fill-bar': {
		'to': {
			transform: 'scaleX(1)',
		}
	}
})
const InnerBarVueJS = styled('div')({
	width: '80%',
  background: '#e68524',
  height: '0.75em',
  transform: 'scaleX(0)',
  transformOrigin: '0 0',
	animation: 'fill-bar 1s forwards',

	'@keyframes fill-bar': {
		'to': {
			transform: 'scaleX(1)',
		}
	}
})
const InnerBarReactJS = styled('div')({
	width: '85%',
  background: '#e24b3e',
  height: '0.75em',
  transform: 'scaleX(0)',
  transformOrigin: '0 0',
	animation: 'fill-bar 1s forwards',

	'@keyframes fill-bar': {
		'to': {
			transform: 'scaleX(1)',
		}
	}
})

export default function WagonAppBar() {
	return (
		<Skills>
			<Container>
				<Title>Python</Title>
				<OuterBar>
					<InnerBarPython />
				</OuterBar>
			</Container>
			<Container>
				<Title>Django</Title>
				<OuterBar>
					<InnerBarDjango />
				</OuterBar>
			</Container>
			<Container>
				<Title>Javascript</Title>
				<OuterBar>
					<InnerBarJavascript />
				</OuterBar>
			</Container>
			<Container>
				<Title>VueJS</Title>
				<OuterBar>
					<InnerBarVueJS />
				</OuterBar>
			</Container>
			<Container>
				<Title>ReactJS</Title>
				<OuterBar>
					<InnerBarReactJS />
				</OuterBar>
			</Container>
		</Skills>
	);
}

// components/snippets/WagonSkills.vue
<template>
  <div class="u-center">
    <section class="skills">
      <div class="skill">
        <h3 class="skill__type">PYTHON</h3>
        <div class="skill__outer-bar">
          <div class="skill__inner-bar skill_python__inner-bar"></div>
        </div>
      </div>
      <div class="skill">
        <h3 class="skill__type">DJANGO</h3>
        <div class="skill__outer-bar">
          <div class="skill__inner-bar skill_django__inner-bar"></div>
        </div>
      </div>
      <div class="skill">
        <h3 class="skill__type">JAVASCRIPT</h3>
        <div class="skill__outer-bar">
          <div class="skill__inner-bar skill_js__inner-bar"></div>
        </div>
      </div>
      <div class="skill">
        <h3 class="skill__type">VUEJS</h3>
        <div class="skill__outer-bar">
          <div class="skill__inner-bar skill_vue__inner-bar"></div>
        </div>
      </div>
      <div class="skill">
        <h3 class="skill__type">REACTJS</h3>
        <div class="skill__outer-bar">
          <div class="skill__inner-bar skill_react__inner-bar"></div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: 'WagonSkills'
}
</script>

<style scoped lang="scss">
.u-center {
  display: flex;
  justify-content: center;
  align-items: center;
}
.skills {
  display: flex;
  flex-direction: column;
  align-self: center;
}
.skill {
  margin: 1em 0;
  position: relative;
  width: 22.5em;
}
.skill__type {
  color: #fff;
  font-weight: 300;
  font-size: 0.8em;
  letter-spacing: 0.145em;
  text-transform: uppercase;
  width: 10em;
}
.skill__outer-bar,
.skill__inner-bar {
  height: 0.75em;
}
.skill__outer-bar {
  margin-top: 1em;
  background: #333;
}
.skill__inner-bar {
  animation: fillBar 1s forwards;
  transform: scaleX(0);
  transform-origin: 0 0;
}
.skill_python__inner-bar {
  width: 95%;
  background: #08475f;
}
.skill_django__inner-bar {
  width: 90%;
  background: #13583e;
}
.skill_js__inner-bar {
  width: 90%;
  background: #ecd51d;
}
.skill_vue__inner-bar {
  width: 80%;
  background: #e68524;
}
.skill_react__inner-bar {
  width: 85%;
  background: #e24b3e;
}
@keyframes fillBar {
  to {
    transform: scaleX(1);
  }
}
</style>
