// src/components/WagonSideBar.tsx
import * as React from 'react';
import { useRouter } from 'next/router'
import Image from 'next/image'
import Link from 'next/link'
import Box, { BoxProps } from '@mui/material/Box';
import Drawer from '@mui/material/Drawer';
import CssBaseline from '@mui/material/CssBaseline';
import List from '@mui/material/List';
import ListItem, { ListItemProps } from '@mui/material/ListItem';
import IconButton, { IconButtonProps } from '@mui/material/IconButton';
import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined';
import AccountCircleOutlinedIcon from '@mui/icons-material/AccountCircleOutlined';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
import EmailOutlinedIcon from '@mui/icons-material/EmailOutlined';
import TwitterIcon from '@mui/icons-material/Twitter';
import GitHubIcon from '@mui/icons-material/GitHub';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import { FontAwesomeIcon, FontAwesomeIconProps } from '@fortawesome/react-fontawesome';
import { faSoundcloud } from '@fortawesome/free-brands-svg-icons';
import { styled } from '@mui/material/styles';

const DRAWER_WIDTH = 60;
const LOGO_PATH = "/images/logo_deer_no_shadow.png";
const SOCIAL_LINKS = {
	TWITTER: "https://twitter.com/metehanglc",
	GITHUB: "https://github.com/mthnglac",
	LINKEDIN: "https://www.linkedin.com/in/metehan-g%C3%BCla%C3%A7-02b337104/",
	SOUNDCLOUD: "https://soundcloud.com/metehan-g-la",
};

const CustomizedBox = styled(Box)<BoxProps>({
	display: 'flex',
	flexDirection: 'column',
	justifyContent: 'space-between',
	height: '100%',
	backgroundColor: '#181818',
});

const AvatarBox = styled(Box)<BoxProps>({
	display: 'flex',
	position: 'relative',
	width: 60,
	height: 104,
	backgroundColor: '#000000',
});

const CustomizedListItem = styled(ListItem)<ListItemProps>({
	justifyContent: 'center',
	margin: '10px 0',
});

const CustomizedIconButton = styled(IconButton)<IconButtonProps>({
	justifyContent: 'center',
	color: "#4d4d4e",
	'&:hover': {
		backgroundColor: 'transparent',
		color: '#08fdd8'
	},
	'&.active': {
		backgroundColor: 'transparent',
		color: '#08fdd8'
	}
});

const CustomizedFontAwesomeIcon = styled(FontAwesomeIcon)<FontAwesomeIconProps>({
	width: '1em !important',
	height: '1em',
	fontSize: 13,
});

export default function PermanentDrawerLeft() {
	const router = useRouter();

  return (
    <Box sx={{ display: 'flex' }}>
      <CssBaseline />
			<Drawer
				sx={{
					width: DRAWER_WIDTH,
					flexShrink: 0,
					'& .MuiDrawer-paper': {
						width: DRAWER_WIDTH,
						boxSizing: 'border-box',
					},
				}}
				variant="permanent"
				anchor="left"
				PaperProps={{
					sx: {
						borderRight: "none",
					}
				}}
			>
				<CustomizedBox>
					<Link href="/">
						<AvatarBox>
							<Image alt="logo" src={LOGO_PATH} layout="fill" objectFit="contain" />
						</AvatarBox>
					</Link>
					<List>
						<CustomizedListItem disablePadding>
							<Link href="/">
								<CustomizedIconButton className={router.pathname === "/" ? "active" : ""} disableRipple aria-label="go to Home page">
									<HomeOutlinedIcon sx={{ fontSize: 24 }} />
								</CustomizedIconButton>
							</Link>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<Link href="/about">
								<CustomizedIconButton className={router.pathname === "/about" ? "active" : ""} disableRipple aria-label="go to About page">
									<AccountCircleOutlinedIcon sx={{ fontSize: 24 }} />
								</CustomizedIconButton>
							</Link>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<Link href="/skills">
								<CustomizedIconButton className={router.pathname === "/skills" ? "active" : ""} disableRipple aria-label="go to Skills page">
									<SettingsOutlinedIcon sx={{ fontSize: 24 }} />
								</CustomizedIconButton>
							</Link>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<Link href="/contact">
								<CustomizedIconButton className={router.pathname === "/contact" ? "active" : ""} disableRipple aria-label="go to Contact page">
									<EmailOutlinedIcon sx={{ fontSize: 24 }} />
								</CustomizedIconButton>
							</Link>
						</CustomizedListItem>
					</List>
					<List>
						<CustomizedListItem disablePadding>
							<CustomizedIconButton href={SOCIAL_LINKS.TWITTER} target="_blank" disableRipple aria-label="go to my Twitter page">
								<TwitterIcon sx={{ fontSize: 13 }} />
							</CustomizedIconButton>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<CustomizedIconButton href={SOCIAL_LINKS.GITHUB} target="_blank" disableRipple aria-label="go to my Github page">
								<GitHubIcon sx={{ fontSize: 13 }} />
							</CustomizedIconButton>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<CustomizedIconButton href={SOCIAL_LINKS.LINKEDIN} target="_blank" disableRipple aria-label="go to my LinkedIn page">
								<LinkedInIcon sx={{ fontSize: 13 }} />
							</CustomizedIconButton>
						</CustomizedListItem>
						<CustomizedListItem disablePadding>
							<CustomizedIconButton href={SOCIAL_LINKS.SOUNDCLOUD} target="_blank" disableRipple aria-label="go to my Soundcloud page">
								<CustomizedFontAwesomeIcon icon={faSoundcloud} />
							</CustomizedIconButton>
						</CustomizedListItem>
					</List>
				</CustomizedBox>
			</Drawer>
    </Box>
  );
}

// components/common/WagonSideBar.vue
<template>
  <v-navigation-drawer
    id="app-drawer"
    v-model="drawer"
    :floating="floating"
    :disable-resize-watcher="disableResizeWatcher"
    :width="navigationDrawerWidth"
    permanent
    app
  >
    <v-img height="100%" style="background-color: #181818;">
      <v-row
        class="fill-height"
        align="stretch"
        justify="space-between"
        no-gutters
      >
        <v-col align-self="start">
          <v-list flat style="padding: 0 0;">
            <v-list-item
              :ripple="false"
              style="
                background-color: black;
                padding-bottom: 15%;
                padding-top: 15%;
              "
              @click="$router.push('/')"
            >
              <v-list-item-avatar id="list-avatar" size="70" tile>
                <v-img :src="avatarImgSrc" contain alt="logo" />
              </v-list-item-avatar>
            </v-list-item>
          </v-list>
        </v-col>
        <v-spacer />
        <v-col align-self="center">
          <v-list flat>
            <v-list-item
              v-for="(item, i) in items"
              :key="i"
              :to="item.link"
              :ripple="false"
              class="v-list-item pages"
              nuxt
              link
            >
              <v-list-item-icon>
                <v-icon size="27">{{ item.icon }}</v-icon>
              </v-list-item-icon>
            </v-list-item>
          </v-list>
        </v-col>
        <v-spacer />
        <v-col align-self="end">
          <v-list flat>
            <v-list-item
              v-for="(item, i) in itemsSocial"
              :key="i"
              :href="item.link"
              :ripple="false"
              target="_blank"
              class="v-list-item social"
              link
            >
              <v-list-item-icon>
                <v-icon size="17">{{ item.icon }}</v-icon>
              </v-list-item-icon>
            </v-list-item>
          </v-list>
        </v-col>
      </v-row>
    </v-img>
  </v-navigation-drawer>
</template>

<script>
export default {
  name: 'WagonSideBar',
  data() {
    return {
      drawer: true,
      floating: true,
      disableResizeWatcher: true,
      navigationDrawerWidth: 60,
      // bgImg: '/bg-space.jpg',
      avatarImgSrc: '/logo_deer_no_shadow.png',
      items: [
        { title: 'Home', icon: 'mdi-home-outline', link: '/' },
        { title: 'About', icon: 'mdi-face-outline', link: '/about' },
        { title: 'Skills', icon: 'mdi-cog-outline', link: '/skills' },
        // { title: 'Blog', icon: 'mdi-coffee-outline', link: '/blog' },
        // { title: 'My Work', icon: 'mdi-eye-outline', link: '/portfolio' },
        { title: 'Contact', icon: 'mdi-email-outline', link: '/contact' },
      ],
      itemsSocial: [
        {
          title: 'Twitter',
          icon: 'mdi-twitter',
          link: 'https://twitter.com/metehanglc',
        },
        {
          title: 'GitHub',
          icon: 'mdi-github',
          link: 'https://github.com/mthnglac',
        },
        {
          title: 'LinkedIn',
          icon: 'mdi-linkedin',
          link:
            'https://www.linkedin.com/in/metehan-g%C3%BCla%C3%A7-02b337104/',
        },
        {
          title: 'SoundCloud',
          icon: 'mdi-soundcloud',
          link: 'https://soundcloud.com/metehan-g-la',
        },
        // {
        //   title: 'Facebook',
        //   icon: 'mdi-facebook',
        //   link: 'https://www.facebook.com/metehan.gulac'
        // }
        // { title: 'Feed', icon: 'mdi-rss', link: 'https://google.com' }
      ],
    }
  },
}
</script>

<style scoped lang="sass">
#app-drawer
  #list-avatar
    position: relative
    right: 75%
  .v-list-item
    &.pages
      padding-left: 29%
    &.social
      padding-left: 35%
    & .v-icon
      color: #4d4d4e
      &:hover
        color: #08fdd8
    &--active
      & .v-icon
        color: #08fdd8
</style>
