// pages/contact.tsx
import * as React from "react";
import Stack, { StackProps } from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import Box, { BoxProps } from "@mui/material/Box";
import Grid, { GridProps } from "@mui/material/Grid";
import Link from "../src/Link";
import { styled } from "@mui/material/styles";
import {
  FontAwesomeIcon,
  FontAwesomeIconProps,
} from "@fortawesome/react-fontawesome";
import {
  faTwitter,
  faGithub,
  faLinkedin,
  faSoundcloud,
} from "@fortawesome/free-brands-svg-icons";
import theme from "../src/theme";
import WagonDartVader from "../src/components/WagonDartVader";

enum SocialLinks {
  TWITTER = "https://twitter.com/metehanglc",
  GITHUB = "https://github.com/mthnglac",
  LINKEDIN = "https://www.linkedin.com/in/metehanglc",
  SOUNDCLOUD = "https://soundcloud.com/metehan-g-la",
}

const CustomizedRootGrid = styled(Grid)<GridProps>(({ theme }) => ({
  alignItems: "stretch",
  height: "100%",

  [theme.breakpoints.down("lg")]: {
    justifyContent: "space-evenly",
  },
  [theme.breakpoints.up("lg")]: {
    justifyContent: "space-around",
  },
}));
const CustomizedLeftSideGrid = styled(Grid)<GridProps>(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  alignItems: "flex-start",
  justifyContent: "space-between",
  zIndex: 1,

  [theme.breakpoints.only("xs")]: {
    marginLeft: "10px",
    marginRight: "10px",
  },
}));
const CustomizedRightSideGrid = styled(Grid)<GridProps>(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  position: "relative",
  zIndex: 0,

  [theme.breakpoints.down("md")]: {
    position: "absolute",
    left: "auto",
    height: "90%",
    opacity: ".15",
  },
}));
const CustomizedResponsiveMarginedBox = styled(Box)<BoxProps>(({ theme }) => ({
  paddingLeft: "10px",
  paddingRight: "10px",
  marginLeft: "120px",

  [theme.breakpoints.only("xs")]: {
    marginLeft: "30px",
  },
  [theme.breakpoints.only("sm")]: {
    marginLeft: "30px",
  },
}));
const CustomizedSkillsIconStack = styled(Stack)<StackProps>({
  marginBottom: "20px",
});
const CustomizedFontAwesomeIcon = styled(FontAwesomeIcon)<FontAwesomeIconProps>(
  {
    padding: "5%",
    fontSize: 30,
  }
);

export default function Contact() {
  return (
    <CustomizedRootGrid container direction="row" columns={12}>
      <CustomizedLeftSideGrid item xs={12} sm={12} md={5} lg={5} xl={5} my={3}>
        <Box>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mb={0}
            ml={2}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;html&gt;
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mb={0}
            ml={4}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;body&gt;
          </Typography>
        </Box>
        <CustomizedResponsiveMarginedBox>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mb={0}
            sx={{
              color: "#515152",
              fontFamily: "'URW Chancery L', cursive",
              fontSize: 16,
              fontStyle: "italic",
            }}
          >
            &lt;h1&gt;
          </Typography>
          <Typography
            variant="h2"
            component="h1"
            gutterBottom
            mb={0}
            color={theme.palette.cyan.main}
            sx={{
              fontWeight: 700,
              fontSize: "1.8rem",
            }}
            data-testid="contact-content-header"
          >
            Contact Me
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mt={0}
            mb={0}
            sx={{
              color: "#515152",
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              fontSize: ".9rem",
            }}
          >
            &lt;/h1&gt;
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mt={2}
            mb={0}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;p&gt;
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mt={0}
            mb={0}
            sx={{
              fontSize: ".9rem",
            }}
          >
            {`I am interested in freelance opportunities - especially ambitious or large projects. However, if you have other request or question, don't hesitate to contact me using below links either.`}
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mt={0}
            mb={2}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;/p&gt;
          </Typography>
          <CustomizedSkillsIconStack direction="row">
            <IconButton
              component={Link}
              href={SocialLinks.TWITTER}
              target="_blank"
              sx={{
                width: "50px",
                height: "50px",
                marginRight: "1rem",
                backgroundColor: "#272727",

                "&:hover": {
                  backgroundColor: "#272727",
                },

                "&.active": {
                  backgroundColor: "#272727",
                },
              }}
            >
              <CustomizedFontAwesomeIcon
                icon={faTwitter}
                data-testid="react-icon"
              />
            </IconButton>
            <IconButton
              component={Link}
              href={SocialLinks.GITHUB}
              target="_blank"
              sx={{
                width: "50px",
                height: "50px",
                marginRight: "1rem",
                backgroundColor: "#272727",

                "&:hover": {
                  backgroundColor: "#272727",
                },

                "&.active": {
                  backgroundColor: "#272727",
                },
              }}
            >
              <CustomizedFontAwesomeIcon
                icon={faGithub}
                data-testid="react-icon"
              />
            </IconButton>
            <IconButton
              component={Link}
              href={SocialLinks.LINKEDIN}
              target="_blank"
              sx={{
                width: "50px",
                height: "50px",
                marginRight: "1rem",
                backgroundColor: "#272727",

                "&:hover": {
                  backgroundColor: "#272727",
                },

                "&.active": {
                  backgroundColor: "#272727",
                },
              }}
            >
              <CustomizedFontAwesomeIcon
                icon={faLinkedin}
                data-testid="react-icon"
              />
            </IconButton>
            <IconButton
              component={Link}
              href={SocialLinks.SOUNDCLOUD}
              target="_blank"
              sx={{
                width: "50px",
                height: "50px",
                marginRight: "1rem",
                backgroundColor: "#272727",

                "&:hover": {
                  backgroundColor: "#272727",
                },

                "&.active": {
                  backgroundColor: "#272727",
                },
              }}
            >
              <CustomizedFontAwesomeIcon
                icon={faSoundcloud}
                data-testid="react-icon"
              />
            </IconButton>
          </CustomizedSkillsIconStack>
        </CustomizedResponsiveMarginedBox>
        <Box>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mb={0}
            ml={4}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;/body&gt;
          </Typography>
          <Typography
            variant="inherit"
            component="p"
            gutterBottom
            mb={0}
            ml={2}
            sx={{
              fontFamily: "'URW Chancery L', cursive",
              fontStyle: "italic",
              color: "#515152",
              fontSize: ".9rem",
            }}
          >
            &lt;/html&gt;
          </Typography>
        </Box>
      </CustomizedLeftSideGrid>
      <CustomizedRightSideGrid item xs={12} sm={12} md={5} lg={5} xl={5} my={5}>
        <WagonDartVader />
      </CustomizedRightSideGrid>
    </CustomizedRootGrid>
  );
}

// pages/contact.vue
<template>
  <v-row class="fill-height" align="stretch" justify="space-around">
    <v-col
      cols="12"
      sm="12"
      md="5"
      lg="5"
      xl="5"
      :style="isMobileLetStyleToLeftCard"
    >
      <v-card
        class="mx-auto"
        width="100%"
        height="100%"
        flat
        color="transparent"
      >
        <v-row class="fill-height" align="stretch" justify="space-between">
          <v-col cols="12" sm="12" md="12" lg="12" xl="12" align-self="start">
            <v-card-text class="custom-top-tags">
              <span class="custom-tags">
                &nbsp;&nbsp;&nbsp;&lt;body&gt;
              </span>
            </v-card-text>
          </v-col>
          <v-spacer />
          <v-col cols="12" sm="12" md="12" lg="12" xl="12" align-self="center">
            <v-card-title class="custom-text-zone card-title">
              <div id="entry">
                <div class="display-2 font-weight-black">
                  {{ contactTitle }}
                </div>
              </div>
            </v-card-title>
            <v-spacer />
            <v-card-text class="custom-text-zone">
              <div>
                I am interested in freelance opportunities - especially
                ambitious or large projects. However, if you have other request
                or question, don't hesitate to contact me using below form
                either.
              </div>
            </v-card-text>
          </v-col>
          <v-spacer />
          <v-spacer />
          <v-col cols="12" sm="12" md="12" lg="12" xl="12" align-self="end">
            <v-card-text class="custom-bottom-tags">
              <span class="custom-tags">
                &nbsp;&nbsp;&nbsp;&lt;/body&gt;<br />
                &lt;/html&gt;
              </span>
            </v-card-text>
          </v-col>
        </v-row>
      </v-card>
    </v-col>
    <v-col
      v-show="$vuetify.breakpoint.xsOnly"
      cols="12"
      sm="12"
      md="12"
      lg="12"
      xl="12"
      align-self="center"
      :style="isMobileLetStyleToRightCard"
    >
      <v-card
        class="mx-auto"
        width="100%"
        height="100%"
        flat
        color="transparent"
      >
        <v-row class="fill-height" align="center" justify="center">
          <v-col cols="12" sm="12" md="12" lg="12" xl="12">
            <v-img
              :src="mainLogoSrc"
              alt="Logo"
              contain
              max-width="500"
              aspect-ratio="1.5"
            />
          </v-col>
        </v-row>
      </v-card>
    </v-col>
    <v-col
      v-show="$vuetify.breakpoint.mdAndUp"
      cols="12"
      sm="12"
      md="5"
      lg="5"
      xl="5"
      class="pr-5"
    >
      <v-card
        class="mx-auto"
        width="100%"
        height="100%"
        flat
        color="transparent"
      >
        <v-row class="fill-height" align="center" justify="center">
          <v-col cols="12" sm="12" md="12" lg="12" xl="12" align-self="center">
            <WagonDartVader />
          </v-col>
        </v-row>
      </v-card>
    </v-col>
  </v-row>
</template>

<script>
import WagonDartVader from '../components/snippets/WagonDartVader'
export default {
  name: 'Contact',
  components: { WagonDartVader },
  data() {
    return {
      windowSize: {
        x: 0,
        y: 0
      },
      contactTitle: 'Contact',
      mainLogoSrc: '/logo-main.png'
    }
  },
  computed: {
    isMobileLetStyleToLeftCard() {
      if (this.windowSize.x < 600) {
        return {
          'z-index': '1',
          position: 'absolute',
          left: '0',
          height: '95%'
        }
      }
      return null
    },
    isMobileLetStyleToRightCard() {
      if (this.windowSize.x < 600) {
        return {
          'z-index': '0',
          opacity: '.4'
        }
      }
      return null
    }
  },
  mounted() {
    this.onResize()
  },
  methods: {
    onResize() {
      this.windowSize = { x: window.innerWidth, y: window.innerHeight }
    }
  }
}
</script>

<style scoped lang="scss">
#entry {
  &:before {
    color: #515152;
    font-family: 'URW Chancery L', cursive;
    font-size: 16px;
    font-style: italic;
    display: block;
    content: '<h1>';
  }
  &:after {
    font-family: 'URW Chancery L', cursive;
    color: #515152;
    font-size: 16px;
    font-style: italic;
    content: '</h1>';
  }
}
.custom-text-zone {
  padding-left: 10%;
  &.card-title {
    color: #08fdd8;
  }
}
.custom-validation-zone {
  padding-left: 8%;
}
.custom-tags {
  font-family: 'URW Chancery L', cursive;
  color: #515152;
  font-size: 20px;
  font-style: italic;
}
.custom-top-tags {
  padding: 0;
}
.custom-bottom-tags {
  padding: 0;
}
</style>
